---
driver:
  name: dokken
  chef_version: latest
  privileged: true # because Docker and SystemD/Upstart
  volumes: [
  '/var/lib/docker', '/var/lib/docker-one', '/var/lib/docker-two'
  ]

transport:
  name: dokken

provisioner:
  name: dokken

verifier:
  name: inspec
  format: doc

platforms:
- name: debian-7
  driver:
    image: dokken/debian-7
    pid_one_command: /sbin/init
  run_list:
  - recipe[chef-apt-docker]

- name: debian-8
  driver:
    image: dokken/debian-8
    pid_one_command: /bin/systemd
  run_list:
  - recipe[chef-apt-docker]

- name: centos-6
  driver:
    image: dokken/centos-6
    platform: rhel
    pid_one_command: /sbin/init
  run_list:
    - recipe[chef-yum-docker]

- name: centos-7
  driver:
    image: dokken/centos-7
    platform: rhel
    pid_one_command: /usr/lib/systemd/systemd
  run_list:
    - recipe[chef-yum-docker]

- name: fedora-latest
  driver:
    image: dokken/fedora-latest
    pid_one_command: /usr/lib/systemd/systemd
  run_list:
    - recipe[chef-yum-docker]

- name: ubuntu-12.04
  driver:
    image: dokken/ubuntu-12.04
    pid_one_command: /sbin/init
  run_list:
  - recipe[chef-apt-docker]

- name: ubuntu-14.04
  driver:
    image: dokken/ubuntu-14.04
    pid_one_command: /sbin/init
  run_list:
  - recipe[chef-apt-docker]

- name: ubuntu-16.04
  driver:
    image: dokken/ubuntu-16.04
    pid_one_command: /bin/systemd
  run_list:
  - recipe[chef-apt-docker]

- name: opensuse-13.2
  driver:
    image: dokken/opensuse-13.2
    pid_one_command: /bin/systemd

- name: amazonlinux
  driver:
    image: dokken/amazonlinux
    pid_one_command: /sbin/init
