---
name: ci

"on":
  pull_request:
  push:
    branches:
      - main

jobs:
  lint-unit:
    uses: sous-chefs/.github/.github/workflows/lint-unit.yml@main
    permissions:
      actions: write
      checks: write
      pull-requests: write
      statuses: write
      issues: write

  integration:
    needs: lint-unit
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os:
          - "almalinux-8"
          - "debian-11"
          - "debian-12"
          - "rockylinux-8"
          - "rockylinux-9"
          - "ubuntu-2004"
          - "ubuntu-2204"
          - "ubuntu-2404"
        suite:
          - "installation-script-main"
          - "installation-script-test"
          - "installation-package"
          - "installation-tarball"
          - "install-and-stop"
        exclude:
          - os: debian-11
            suite: installation-script-test
          - os: debian-12
            suite: installation-script-test
          - os: almalinux-8
            suite: installation-script-main
          - os: almalinux-8
            suite: installation-script-test
          - os: rockylinux-8
            suite: installation-script-main
          - os: rockylinux-8
            suite: installation-script-test
          - os: rockylinux-9
            suite: installation-script-main
          - os: rockylinux-9
            suite: installation-script-test
      fail-fast: false

    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Install Chef
        uses: actionshub/chef-install@3.0.0
      - name: Dokken
        uses: actionshub/test-kitchen@3.0.0
        env:
          CHEF_VERSION: latest
          CHEF_LICENSE: accept-no-persist
          KITCHEN_LOCAL_YAML: kitchen.dokken.yml
        with:
          suite: ${{ matrix.suite }}
          os: ${{ matrix.os }}

  integration-amazonlinux:
    needs: lint-unit
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        os:
          - amazonlinux-2
        suite:
          - "installation-tarball"
          - "install-and-stop"
      fail-fast: false

    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Install Chef
        uses: actionshub/chef-install@3.0.0
      - name: Dokken
        uses: actionshub/test-kitchen@3.0.0
        env:
          CHEF_VERSION: latest
          CHEF_LICENSE: accept-no-persist
          KITCHEN_LOCAL_YAML: kitchen.dokken.yml
        with:
          suite: ${{ matrix.suite }}
          os: ${{ matrix.os }}

  integration-smoke:
    needs: lint-unit
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os:
          - "almalinux-8"
          - "almalinux-9"
          - "debian-11"
          - "debian-12"
          - "rockylinux-8"
          - "rockylinux-9"
          - "ubuntu-2004"
          - "ubuntu-2204"
          - "ubuntu-2404"
        suite:
          - "smoke"
      fail-fast: false

    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Install VirtualBox & Vagrant
        run: |
          sudo apt update && sudo apt install virtualbox
          wget -O- https://apt.releases.hashicorp.com/gpg | sudo gpg --dearmor -o /usr/share/keyrings/hashicorp-archive-keyring.gpg
          echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/hashicorp.list
          sudo apt update && sudo apt install vagrant
      - name: Install Chef
        uses: actionshub/chef-install@3.0.0
      - name: Dokken
        uses: actionshub/test-kitchen@3.0.0
        env:
          CHEF_VERSION: latest
          CHEF_LICENSE: accept-no-persist
        with:
          suite: ${{ matrix.suite }}
          os: ${{ matrix.os }}
